sm8350-common: Define missing Dolby HALs
The following HALs in device manifest are not declared in FCM <= level 5:
  vendor.dolby.hardware.dms@2.0::IDms/default
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.dolby.hardware.dms@2.0::IDms/default
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 5.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 5 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success
INCOMPATIBLE

Signed-off-by: RobertGarciaa <chae0218@naver.com>